################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal.c \
D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_cortex.c \
D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_dma.c \
D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_dma_ex.c \
D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_exti.c \
D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_flash.c \
D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_flash_ex.c \
D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_flash_ramfunc.c \
D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_gpio.c \
D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_i2c.c \
D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_i2c_ex.c \
D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_icache.c \
D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_pwr.c \
D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_pwr_ex.c \
D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rcc.c \
D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rcc_ex.c \
D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_tim.c \
D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_tim_ex.c \
D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_uart.c \
D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_uart_ex.c 

OBJS += \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_cortex.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_dma.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_dma_ex.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_exti.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_flash.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_flash_ex.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_flash_ramfunc.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_gpio.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_i2c.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_i2c_ex.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_icache.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_pwr.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_pwr_ex.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rcc.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rcc_ex.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_tim.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_tim_ex.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_uart.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_uart_ex.o 

C_DEPS += \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_cortex.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_dma.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_dma_ex.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_exti.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_flash.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_flash_ex.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_flash_ramfunc.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_gpio.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_i2c.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_i2c_ex.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_icache.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_pwr.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_pwr_ex.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rcc.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rcc_ex.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_tim.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_tim_ex.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_uart.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_uart_ex.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal.o: D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal.c Drivers/STM32L5xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 '-DMBEDTLS_CONFIG_FILE="mbedtls_config.h"' -DUSE_HAL_DRIVER -DSTM32L562xx -DDEBUG -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I../MBEDTLS/App -I../../Middlewares/Third_Party/mbedTLS/include/mbedtls -I../../Middlewares/Third_Party/mbedTLS/include -I../../Drivers/BSP/STM32L562E-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_cortex.o: D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_cortex.c Drivers/STM32L5xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 '-DMBEDTLS_CONFIG_FILE="mbedtls_config.h"' -DUSE_HAL_DRIVER -DSTM32L562xx -DDEBUG -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I../MBEDTLS/App -I../../Middlewares/Third_Party/mbedTLS/include/mbedtls -I../../Middlewares/Third_Party/mbedTLS/include -I../../Drivers/BSP/STM32L562E-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_dma.o: D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_dma.c Drivers/STM32L5xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 '-DMBEDTLS_CONFIG_FILE="mbedtls_config.h"' -DUSE_HAL_DRIVER -DSTM32L562xx -DDEBUG -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I../MBEDTLS/App -I../../Middlewares/Third_Party/mbedTLS/include/mbedtls -I../../Middlewares/Third_Party/mbedTLS/include -I../../Drivers/BSP/STM32L562E-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_dma_ex.o: D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_dma_ex.c Drivers/STM32L5xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 '-DMBEDTLS_CONFIG_FILE="mbedtls_config.h"' -DUSE_HAL_DRIVER -DSTM32L562xx -DDEBUG -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I../MBEDTLS/App -I../../Middlewares/Third_Party/mbedTLS/include/mbedtls -I../../Middlewares/Third_Party/mbedTLS/include -I../../Drivers/BSP/STM32L562E-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_exti.o: D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_exti.c Drivers/STM32L5xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 '-DMBEDTLS_CONFIG_FILE="mbedtls_config.h"' -DUSE_HAL_DRIVER -DSTM32L562xx -DDEBUG -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I../MBEDTLS/App -I../../Middlewares/Third_Party/mbedTLS/include/mbedtls -I../../Middlewares/Third_Party/mbedTLS/include -I../../Drivers/BSP/STM32L562E-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_flash.o: D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_flash.c Drivers/STM32L5xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 '-DMBEDTLS_CONFIG_FILE="mbedtls_config.h"' -DUSE_HAL_DRIVER -DSTM32L562xx -DDEBUG -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I../MBEDTLS/App -I../../Middlewares/Third_Party/mbedTLS/include/mbedtls -I../../Middlewares/Third_Party/mbedTLS/include -I../../Drivers/BSP/STM32L562E-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_flash_ex.o: D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_flash_ex.c Drivers/STM32L5xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 '-DMBEDTLS_CONFIG_FILE="mbedtls_config.h"' -DUSE_HAL_DRIVER -DSTM32L562xx -DDEBUG -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I../MBEDTLS/App -I../../Middlewares/Third_Party/mbedTLS/include/mbedtls -I../../Middlewares/Third_Party/mbedTLS/include -I../../Drivers/BSP/STM32L562E-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_flash_ramfunc.o: D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_flash_ramfunc.c Drivers/STM32L5xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 '-DMBEDTLS_CONFIG_FILE="mbedtls_config.h"' -DUSE_HAL_DRIVER -DSTM32L562xx -DDEBUG -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I../MBEDTLS/App -I../../Middlewares/Third_Party/mbedTLS/include/mbedtls -I../../Middlewares/Third_Party/mbedTLS/include -I../../Drivers/BSP/STM32L562E-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_gpio.o: D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_gpio.c Drivers/STM32L5xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 '-DMBEDTLS_CONFIG_FILE="mbedtls_config.h"' -DUSE_HAL_DRIVER -DSTM32L562xx -DDEBUG -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I../MBEDTLS/App -I../../Middlewares/Third_Party/mbedTLS/include/mbedtls -I../../Middlewares/Third_Party/mbedTLS/include -I../../Drivers/BSP/STM32L562E-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_i2c.o: D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_i2c.c Drivers/STM32L5xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 '-DMBEDTLS_CONFIG_FILE="mbedtls_config.h"' -DUSE_HAL_DRIVER -DSTM32L562xx -DDEBUG -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I../MBEDTLS/App -I../../Middlewares/Third_Party/mbedTLS/include/mbedtls -I../../Middlewares/Third_Party/mbedTLS/include -I../../Drivers/BSP/STM32L562E-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_i2c_ex.o: D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_i2c_ex.c Drivers/STM32L5xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 '-DMBEDTLS_CONFIG_FILE="mbedtls_config.h"' -DUSE_HAL_DRIVER -DSTM32L562xx -DDEBUG -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I../MBEDTLS/App -I../../Middlewares/Third_Party/mbedTLS/include/mbedtls -I../../Middlewares/Third_Party/mbedTLS/include -I../../Drivers/BSP/STM32L562E-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_icache.o: D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_icache.c Drivers/STM32L5xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 '-DMBEDTLS_CONFIG_FILE="mbedtls_config.h"' -DUSE_HAL_DRIVER -DSTM32L562xx -DDEBUG -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I../MBEDTLS/App -I../../Middlewares/Third_Party/mbedTLS/include/mbedtls -I../../Middlewares/Third_Party/mbedTLS/include -I../../Drivers/BSP/STM32L562E-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_pwr.o: D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_pwr.c Drivers/STM32L5xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 '-DMBEDTLS_CONFIG_FILE="mbedtls_config.h"' -DUSE_HAL_DRIVER -DSTM32L562xx -DDEBUG -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I../MBEDTLS/App -I../../Middlewares/Third_Party/mbedTLS/include/mbedtls -I../../Middlewares/Third_Party/mbedTLS/include -I../../Drivers/BSP/STM32L562E-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_pwr_ex.o: D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_pwr_ex.c Drivers/STM32L5xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 '-DMBEDTLS_CONFIG_FILE="mbedtls_config.h"' -DUSE_HAL_DRIVER -DSTM32L562xx -DDEBUG -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I../MBEDTLS/App -I../../Middlewares/Third_Party/mbedTLS/include/mbedtls -I../../Middlewares/Third_Party/mbedTLS/include -I../../Drivers/BSP/STM32L562E-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rcc.o: D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rcc.c Drivers/STM32L5xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 '-DMBEDTLS_CONFIG_FILE="mbedtls_config.h"' -DUSE_HAL_DRIVER -DSTM32L562xx -DDEBUG -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I../MBEDTLS/App -I../../Middlewares/Third_Party/mbedTLS/include/mbedtls -I../../Middlewares/Third_Party/mbedTLS/include -I../../Drivers/BSP/STM32L562E-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rcc_ex.o: D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rcc_ex.c Drivers/STM32L5xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 '-DMBEDTLS_CONFIG_FILE="mbedtls_config.h"' -DUSE_HAL_DRIVER -DSTM32L562xx -DDEBUG -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I../MBEDTLS/App -I../../Middlewares/Third_Party/mbedTLS/include/mbedtls -I../../Middlewares/Third_Party/mbedTLS/include -I../../Drivers/BSP/STM32L562E-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_tim.o: D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_tim.c Drivers/STM32L5xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 '-DMBEDTLS_CONFIG_FILE="mbedtls_config.h"' -DUSE_HAL_DRIVER -DSTM32L562xx -DDEBUG -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I../MBEDTLS/App -I../../Middlewares/Third_Party/mbedTLS/include/mbedtls -I../../Middlewares/Third_Party/mbedTLS/include -I../../Drivers/BSP/STM32L562E-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_tim_ex.o: D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_tim_ex.c Drivers/STM32L5xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 '-DMBEDTLS_CONFIG_FILE="mbedtls_config.h"' -DUSE_HAL_DRIVER -DSTM32L562xx -DDEBUG -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I../MBEDTLS/App -I../../Middlewares/Third_Party/mbedTLS/include/mbedtls -I../../Middlewares/Third_Party/mbedTLS/include -I../../Drivers/BSP/STM32L562E-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_uart.o: D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_uart.c Drivers/STM32L5xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 '-DMBEDTLS_CONFIG_FILE="mbedtls_config.h"' -DUSE_HAL_DRIVER -DSTM32L562xx -DDEBUG -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I../MBEDTLS/App -I../../Middlewares/Third_Party/mbedTLS/include/mbedtls -I../../Middlewares/Third_Party/mbedTLS/include -I../../Drivers/BSP/STM32L562E-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_uart_ex.o: D:/PanWorkSpace/CCE/test_app_1/test_apps/thermostat/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_uart_ex.c Drivers/STM32L5xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 '-DMBEDTLS_CONFIG_FILE="mbedtls_config.h"' -DUSE_HAL_DRIVER -DSTM32L562xx -DDEBUG -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I../MBEDTLS/App -I../../Middlewares/Third_Party/mbedTLS/include/mbedtls -I../../Middlewares/Third_Party/mbedTLS/include -I../../Drivers/BSP/STM32L562E-DK -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Drivers-2f-STM32L5xx_HAL_Driver

clean-Drivers-2f-STM32L5xx_HAL_Driver:
	-$(RM) ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal.d ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal.o ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_cortex.d ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_cortex.o ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_dma.d ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_dma.o ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_dma_ex.d ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_dma_ex.o ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_exti.d ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_exti.o ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_flash.d ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_flash.o ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_flash_ex.d ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_flash_ex.o ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_flash_ramfunc.d ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_flash_ramfunc.o ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_gpio.d ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_gpio.o ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_i2c.d ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_i2c.o ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_i2c_ex.d ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_i2c_ex.o ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_icache.d ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_icache.o ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_pwr.d ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_pwr.o ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_pwr_ex.d ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_pwr_ex.o ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rcc.d ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rcc.o ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rcc_ex.d ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rcc_ex.o ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_tim.d ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_tim.o ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_tim_ex.d ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_tim_ex.o ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_uart.d ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_uart.o ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_uart_ex.d ./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_uart_ex.o

.PHONY: clean-Drivers-2f-STM32L5xx_HAL_Driver

